version: "3"

services:
  mongo:
    image: "mongo:4.0.0"
    ports:
      - "27017:27017"
    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: password
#      MONGO_INITDB_DATABASE: sample
